### ISSUE TITLE
Just for image hosting

### ISSUE THREAD

**Issue by onns** [xmu-campus/2021-spring#1]
![微信图片_20210305123633](https://user-images.githubusercontent.com/16622934/110067858-817af580-7daf-11eb-9009-06441eb109e1.jpg)
![微信图片_20210305123628](https://user-images.githubusercontent.com/16622934/110067887-893a9a00-7daf-11eb-9f46-ac1e6cae7b85.png)

**Comment by LinWencong** [comment]
Baidu 2021 Spring
![WechatIMG42](https://user-images.githubusercontent.com/27762366/110078711-1affd280-7dc3-11eb-93d0-c6fc6405663d.jpeg)
